version: '3.3'

services:
  app:
    build: .
    image: node-app
    ports:
      - '4000:4000'
    depends_on:
      - redis
    volumes:
      - .:/src
    networks:
      - node-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - node-network

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
